export interface PrebuiltBank {
  id: string;
  name: string;
  industry: string;
  standard: string;
  auditType: string;
  questions: string[];
}

// Pre-built audit question banks. Users copy from these into their own
// templates and can mix questions across banks.
export const PrebuiltBanks: PrebuiltBank[] = [
  {
    id: 'gen-5s',
    name: 'General 5S Walkthrough',
    industry: 'General',
    standard: 'ISO 9001',
    auditType: '5S',
    questions: [
      'Are all work surfaces clean and free of debris?',
      'Are tools and parts returned to their designated locations?',
      'Are aisles and walkways clear and marked?',
      'Are visual standards (e.g. shadow boards) in place and current?',
      'Is the area free of slip/trip hazards?',
      'Are personal items stored outside the work zone?',
      'Are SOPs and work instructions posted and visible?',
      'Are containers and bins labeled correctly?',
      'Are unused tools, parts, or fixtures removed from the work area?',
      'Is housekeeping documented for the prior shift?',
      'Are floor markings intact and visible?',
      'Are first-aid and emergency supplies clearly marked?',
      'Are PPE storage stations stocked?',
      'Are recycling and waste streams separated correctly?',
      'Are 5S audit results posted near the work cell?',
    ],
  },
  {
    id: 'gen-safety',
    name: 'Safety Walk',
    industry: 'General',
    standard: 'OSHA',
    auditType: 'Safety Walk',
    questions: [
      'Are emergency exits unobstructed and clearly marked?',
      'Are fire extinguishers inspected and in date?',
      'Are eye wash stations functional and accessible?',
      'Is electrical panel access unobstructed (36 in clearance)?',
      'Are spill kits fully stocked and accessible?',
      'Are SDSs available for chemicals in the area?',
      'Is appropriate PPE being worn for the task?',
      'Are guards in place and undamaged on all machines?',
      'Is LOTO equipment available and being used during maintenance?',
      'Are ladders and step stools inspected and serviceable?',
      'Are floors free of slip, trip, or fall hazards?',
      'Are pinch-point areas clearly identified?',
      'Are emergency stops accessible on running equipment?',
      'Is the first-aid kit complete and within expiration?',
      'Are evacuation maps posted at each exit?',
    ],
  },
  {
    id: 'gen-process',
    name: 'Process Audit',
    industry: 'General',
    standard: 'ISO 9001',
    auditType: 'Process Audit',
    questions: [
      'Is the current work instruction posted at the workstation?',
      'Are operators trained and current on the process?',
      'Is the process operating within stated parameters?',
      'Is in-process inspection performed at the documented frequency?',
      'Are nonconforming parts segregated when detected?',
      'Are gauges and instruments calibrated and within due date?',
      'Are setup verification records on file?',
      'Are records of process changes traceable?',
      'Are reaction plans in place for out-of-control conditions?',
      'Is the customer-specific requirement reflected in the process?',
      'Is rework documented and approved?',
      'Are tooling change-outs tracked and verified?',
      'Are operators using the latest revision of the control plan?',
      'Is material traceability maintained throughout the process?',
      'Are environmental conditions (temp, humidity) monitored where required?',
    ],
  },
  {
    id: 'iso-9001-lpa-l1',
    name: 'LPA Layer 1 (Operator)',
    industry: 'General',
    standard: 'ISO 9001',
    auditType: 'LPA Layer 1',
    questions: [
      'Is the latest revision of the work instruction in use?',
      'Are tools and gauges within calibration?',
      'Is PPE worn correctly?',
      'Is the work cell 5S-compliant at this moment?',
      'Are nonconforming parts placed in the correct quarantine bin?',
      'Are setup pieces marked and stored properly?',
      'Has the first-piece inspection been completed?',
      'Are torque settings verified per spec?',
      'Are travelers and routers completed at each step?',
      'Are operators trained for the current job (training record on file)?',
      'Is the area free of expired material?',
      'Are critical-to-quality features identified visually?',
      'Are reject parts removed from the work area?',
      'Are bins and racks labeled with current lot information?',
      'Are operators following the documented sequence of operations?',
    ],
  },
  {
    id: 'iso-9001-lpa-l2',
    name: 'LPA Layer 2 (Supervisor)',
    industry: 'General',
    standard: 'ISO 9001',
    auditType: 'LPA Layer 2',
    questions: [
      'Are Layer 1 audits closed out within the required window?',
      'Are operator findings escalated and tracked to closure?',
      'Are reaction plans being followed for out-of-control conditions?',
      'Is the daily production board current with quality metrics?',
      'Have all calibrations come due in the period been completed?',
      'Are nonconforming material disposition decisions documented?',
      'Are SPC charts being reviewed at the supervisor level?',
      'Are training gaps identified during the last quarter being closed?',
      'Are preventive maintenance work orders current?',
      'Are layered audits planned for the upcoming week?',
      'Are escalations to engineering documented and acknowledged?',
      'Are operator concerns logged and reviewed in shift handoff?',
      'Are customer-specific requirements visible in the work cell?',
      'Are improvement actions from previous audits implemented?',
      'Are metrics (FPY, scrap, rework) trending in the right direction?',
    ],
  },
  {
    id: 'iso-9001-lpa-l3',
    name: 'LPA Layer 3 (Manager)',
    industry: 'General',
    standard: 'ISO 9001',
    auditType: 'LPA Layer 3',
    questions: [
      'Are Layer 2 audits completed by the required date?',
      'Is the layered audit program self-sustaining (no manager nagging)?',
      'Are repeated findings tracked across multiple Layer 1 audits?',
      'Are corrective actions verified for effectiveness?',
      'Are budget and staffing aligned to quality objectives?',
      'Are customer complaints reviewed at management level?',
      'Are management-review actions trending to completion?',
      'Are external audit findings closed on schedule?',
      'Are supplier performance reviews current?',
      'Are key process indicators reviewed weekly?',
      'Are nonconformance trends discussed at leadership team meetings?',
      'Are training records reviewed quarterly?',
      'Is the company\'s quality policy understood at the floor level?',
      'Are continual improvement projects funded and staffed?',
      'Is the management system audit-ready at all times?',
    ],
  },
  {
    id: 'iatf-control-plan',
    name: 'Automotive — Control Plan Audit',
    industry: 'Automotive',
    standard: 'IATF 16949',
    auditType: 'Process Audit',
    questions: [
      'Is the control plan current and matched to the part revision?',
      'Are control characteristics matching the PFMEA?',
      'Are SPC charts maintained for special characteristics?',
      'Are reaction plans documented for out-of-control conditions?',
      'Is the gage R&R study on file for the measurement system?',
      'Are control-plan inspection frequencies being met?',
      'Are operators trained on control-plan changes?',
      'Are first-piece, in-process, and last-piece inspections recorded?',
      'Are CSRs (customer-specific requirements) addressed in the control plan?',
      'Are error-proofing devices in place and verified each shift?',
      'Are traceability records linking parts to specific control-plan revisions?',
      'Are non-conforming parts segregated and documented?',
      'Are control-plan owners identified and current?',
      'Are 8D problem-solving records linked to control-plan updates?',
      'Are layered audits referencing the control plan?',
    ],
  },
  {
    id: 'aero-foreign-object',
    name: 'Aerospace — Foreign Object Damage (FOD) Audit',
    industry: 'Aerospace',
    standard: 'AS9100',
    auditType: 'Safety Walk',
    questions: [
      'Are FOD bins available and being used in the work cell?',
      'Are tools accounted for at end of shift (tool control)?',
      'Are fasteners and hardware contained in approved storage?',
      'Are FOD signs posted at entry to controlled areas?',
      'Is the area free of loose paper, plastic, or wire trimmings?',
      'Are operators trained in FOD prevention this calendar year?',
      'Are FOD inspections documented at shift end?',
      'Are pockets emptied before entering the work zone?',
      'Are tooling logs reviewed and closed out daily?',
      'Are flooring and grating free of debris?',
      'Are hand tools tethered when used near aircraft openings?',
      'Are FOD incidents logged and trended?',
      'Are vacuum and sweep cycles performed on schedule?',
      'Are contractors and visitors briefed on FOD policy?',
      'Are FOD audit findings reviewed monthly with leadership?',
    ],
  },
  {
    id: 'food-haccp',
    name: 'Food & Beverage — HACCP Walk',
    industry: 'Food & Beverage',
    standard: 'ISO 9001',
    auditType: 'Process Audit',
    questions: [
      'Are CCP records being completed at the required frequency?',
      'Are corrective actions for CCP deviations documented?',
      'Are sanitation cycles performed and verified?',
      'Are allergen controls in place at change-over?',
      'Are temperatures within the cold-chain limits?',
      'Are operators trained on personal hygiene policy?',
      'Are pest-control reports current?',
      'Are foreign-object detection systems verified each shift?',
      'Are calibration records for thermometers current?',
      'Are traceability records (lot, supplier) complete?',
      'Are non-conforming product holds being managed correctly?',
      'Are visitors and contractors following hygiene rules?',
      'Are receiving inspections documented?',
      'Are mock recalls performed annually?',
      'Are CIP/SIP cycles validated and verified?',
    ],
  },
  {
    id: 'mfg-prestart',
    name: 'Manufacturing — Pre-Start Equipment Check',
    industry: 'Manufacturing',
    standard: 'OSHA',
    auditType: 'Safety Walk',
    questions: [
      'Is the emergency stop accessible and tested?',
      'Are guards in place and undamaged?',
      'Is air pressure within normal range?',
      'Is hydraulic fluid level within marked range?',
      'Are lubrication points serviced per PM schedule?',
      'Are tooling fasteners torqued to spec?',
      'Is the area free of oil or coolant leaks?',
      'Are interlocks functional and tested?',
      'Are operator controls labeled and legible?',
      'Are warning beacons functional?',
      'Is the operator log signed off for the prior shift?',
      'Are calibration tags current on attached gauges?',
      'Is the cleanout/scrap chute clear?',
      'Are start-up procedures posted at the workstation?',
      'Is the area free of debris that could enter the machine?',
    ],
  },
];
